<?php

namespace Drupal\citizen_migrate;

class Image extends TagBase {

  /**
   * @inheritdoc
   */
  public function convertTag(string $tagname): \DOMElement {
    return parent::convertTag($tagname); // TODO: Change the autogenerated stub
  }

  /**
   * @inheritdoc
   */
  public function processTag(): string {
    return parent::processTag(); // TODO: Change the autogenerated stub
  }

  /**
   * @inheritdoc
   */
  public function removeTag(): bool {
    return parent::removeTag(); // TODO: Change the autogenerated stub
  }

  /**
   * @inheritdoc
   */
  public function transformTag(): bool {
    return parent::transformTag(); // TODO: Change the autogenerated stub
  }

}