<?php

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function citizen_domain_form_node_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

  // Hide the Domain Access "Send to all affiliates" option on node edit forms.
  if(isset($form['field_domain_all_affiliates'])){
    // Hide the field from view.
    //$form['field_domain_all_affiliates']['#attributes']['hidden'] = 'hidden';
  }

  // Sync the "Domain Source" value to the "Domain Access" value.
  if(isset($form['field_domain_access']) && isset($form['field_domain_source'])){
    // Match the "Domain Source" value to the "Domain Access" default value.
    $form['field_domain_source']['widget']['#default_value'][0] = $form['field_domain_access']['widget']['#default_value'];

    // Attach the JS script that will sync the "Domain Source" value
    // to the "Domain Access" value when changed by the user.
    $form['#attached']['library'][] = 'citizen_domain/citizen_domain';
  }

  // Update "Show On" values to match "Domain Access"
  if(isset($form['field_domain_access'])){
    $domainAccess = $form['field_domain_access']['widget']['#default_value'];
    if (is_array($domainAccess)) {
      $domainAccess = array_pop($domainAccess);
    }
  // Set "Show on" values here
  }
}
