<?php
use \Drupal\Core\Field\FieldStorageDefinitionInterface;
use \Drupal\Core\Entity\FieldableEntityInterface;

// this callback is referenced by name in the field_livewhale_group config
// in the "allowed_values_function" config option
function callback_livewhale_allowed_group_options(FieldStorageDefinitionInterface $definition, FieldableEntityInterface $entity = NULL, &$cacheable = TRUE) {
	if($definition->getName() === 'field_livewhale_group'){
		$livewhale = \Drupal::service('livewhale.api');
		$groups = $livewhale->getGroups();
		
		$values = [];
		foreach($groups as $g){
			$values[$g['id']] = $g['fullname'];
		}
		return $values;
	}
}