<?php

/**
 * @file
 * Primary module hooks for Citizen Profile Sync module.
 */

/**
 * Cron job to connect to profiles endpoint and
 *  sync to Profiles content type
 */
function citizen_profile_sync_cron() {
  $profileSyncService = \Drupal::service('citizen_profile_sync.profile_sync_service');

  $http_client = \Drupal::httpClient();

  $url = "https://athena.apps.uwec.edu/api/profiles.json";

  $apikey = '36dadd0fab31edb063666ef8f43e595d';

  $query_string = '?apikey=' . $apikey;
  $active_query_string = $query_string . '&isactive=1';

  //todo add try-catch block
  $response = $http_client->get($url . $active_query_string);

  if ($response->getStatusCode() == 200) {
    // Process the response body.
    $data = json_decode($response->getBody());
    // Do something with $data.
    $profiles = (array) $data;

    $profileSyncService->syncProfiles($profiles);
  }
  else {
    // Handle the error, e.g., log it or throw an exception.
    \Drupal::logger('citizen_profile_sync')
      ->error('Error accessing API: @code - @message', [
        '@code' => $response->getStatusCode(),
        '@message' => $response->getReasonPhrase(),
      ]);
  }

  $inactive_query_string = $query_string . '&isactive=0';

  $response = $http_client->get($url . $inactive_query_string);

  if ($response->getStatusCode() == 200) {

    $data = json_decode($response->getBody());

    $inactive_profiles = (array) $data;

    $profileSyncService->deactivateProfiles($inactive_profiles);


  }
  else {
    // Handle the error, e.g., log it or throw an exception.
    \Drupal::logger('citizen_profile_sync')
      ->error('Error accessing API: @code - @message', [
        '@code' => $response->getStatusCode(),
        '@message' => $response->getReasonPhrase(),
      ]);
  }
}

function citizen_profile_sync_form_alter(&$form, $form_state, $form_id) {
  /* Find the current user */
  $user = \Drupal::currentUser();
  $userId = $user->id();
  if ($form_id === 'node_bios_edit_form') {
    if ($userId == 1) {
      $form['field_athena_id']['#access'] = TRUE;
      $form['field_active']['#access'] = TRUE;
      $form['field_username']['#access'] = TRUE;
      $form['field_email']['#access'] = TRUE;
      $form['field_phone']['#access'] = TRUE;
      $form['field_first_name']['#access'] = TRUE;
      $form['field_last_name']['#access'] = TRUE;
      $form['field_position']['#access'] = TRUE;
      $form['field_import_date']['#access'] = TRUE;
    } else {
      $form['field_athena_id']['#access'] = FALSE;
      $form['field_active']['#access'] = FALSE;
      $form['field_username']['#access'] = FALSE;
      $form['field_email']['#access'] = FALSE;
      $form['field_phone']['#access'] = FALSE;
      $form['field_first_name']['#access'] = FALSE;
      $form['field_last_name']['#access'] = FALSE;
      $form['field_position']['#access'] = FALSE;
      $form['field_import_date']['#access'] = FALSE;
    }
  }
}
