<?php

/**
 * @file
 * Primary module hooks for Citizen Profile Sync module.
 */

use \Drupal\Core\Http\ClientFactory;
use Drupal\your_module\ProfileSyncService;
use Symfony\Component\DependencyInjection\ContainerInterface;


/**
 * Cron job to connect to profiles endpoint and
 *  sync to Profiles content type
 */
function citizen_profile_sync_cron() {
  $profileSyncService = \Drupal::service('citizen_profile_sync.profile_sync_service');

  $http_client = \Drupal::httpClient();

  $url = "https://athena.apps.uwec.edu/api/profiles.json";

  $apikey = '36dadd0fab31edb063666ef8f43e595d';

  $query_string = '?apikey=' . $apikey;
  $query_string .= '&isactive=1';

  //todo add try-catch block
  $response = $http_client->get($url . $query_string);

  if ($response->getStatusCode() == 200) {
    // Process the response body.
    $data = json_decode($response->getBody());
    // Do something with $data.
    $profiles = (array) $data;

    $profileSyncService->syncProfiles($profiles);
  }
  else {
    // Handle the error, e.g., log it or throw an exception.
    \Drupal::logger('your_module')
      ->error('Error accessing API: @code - @message', [
        '@code' => $response->getStatusCode(),
        '@message' => $response->getReasonPhrase(),
      ]);
  }
}
