# See the EC-MIGRATE.md file for detailed information about how to use this file.

# Source defaults: Common settings for all migrations.
cm_defaults:
  source:
    track_changes: true
    track_last_imported: true # Requires patch: https://www.drupal.org/files/issues/2022-05-31/3198608-43.patch
    log_data: true
    batch_size: 500

# JSON Source settings.
json_defaults:
  source:
    data_fetcher_plugin: http
    data_parser_plugin: json
    headers:
      'Accept-Encoding': 'gzip,deflate,br'
      'Accept': 'application/json'
    item_selector: /
    constants:
      limit: null
      unit_id: null
      isactive: null
      ispublished: null
      system_id: null
      migrating_to_drupal: null
    data_fetcher_options:
      iterator:
        limit: '@constants/limit'

# CSV Source default settings.
csv_defaults:
  source:
    delimiter: ','
    enclosure: '"'
    header_offset: 0

# User defaults: Common settings for all User accounts.
user_defaults:
  source:
    cm_type: user

# File defaults: Common settings for all File migrations.
filemedia_doc_defaults:
  urls: 'https://athena.apps.uwec.edu/api/documents.json'
  fields:
    -
      name: id
      label: ID
      selector: id
    -
      name: url
      label: URL
      selector: url
    -
      name: title
      label: Title
      selector: title
    -
      name: isactive
      label: isActive
      selector: isactive
    -
      name: created_at
      label: Created
      selector: created_at
    -
      name: unit_ids
      label: unitIds
      selector: unit_ids
    -
      name: keyword_ids
      label: Keywords
      selector: keyword_ids
    -
      name: category_ids
      label: Categories
      selector: category_ids
  ids:
    id:
      type: integer

# Media defaults: Common settings for all Media migrations.
filmed_img_defaults:
  source:
    cm_type: media

# Taxonomy defaults for common settings across all Vocabulary/Term migrations.
taxonomy_defaults:
  source:
    cm_type: taxonomy

# Paragraph defaults for common settings across all Paragraph migrations.
paragraph_defaults:
  source:
    cm_type: paragraph

# Node defaults for common settings across all Node migrations.
node_defaults:
#  source:
#    cm_type: node
  process:
#    created: created
    changed:
      plugin: format_date
      source: updated_at
      from_format: 'Y-m-d H:i:s'
      to_format: 'U'
    status: isactive
    langcode:
      plugin: default_value
      default_value: en
    uid:
      plugin: default_value
      default_value: 1
    field_domain_access:
      plugin: default_value
      default_value: uwec_docksal_site
    field_domain_source:
      plugin: default_value
      default_value: uwec_docksal_site

# Table defaults for common settings of individual table migrations.
table_defaults:
  source:
    cm_type: table
